kind: pipeline
type: kubernetes
name: Continuous Integration

steps:
- name: integrate
  image: gautada/builder:v1.21.4_v3.2.3
  privileged: true
  environment:
    DOCKER_USERNAME:
      from_secret: username.docker.io
    DOCKER_PASSWORD:
      from_secret: password.docker.io
    ALPINE_TAG: 3.14.1
    OCI_CONTAINER: fluentd
    OCI_REPOSITORY: docker://docker.io/gautada
    OCI_VERSION: v1.14.0.5
  commands:
  - buildah login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD docker.io
  - buildah bud --build-arg ALPINE_TAG=$ALPINE_TAG --build-arg BRANCH=$OCI_VERSION --file Containerfile --tag localhost/$OCI_CONTAINER:dev
  - buildah push localhost/$OCI_CONTAINER:dev $OCI_REPOSITORY/$OCI_CONTAINER:$OCI_VERSION

trigger:
  branch:
  - main



